### ISSUE TITLE
Provide environment instructions

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/cloud-optimized-geospatial-formats-guide#20]
We should provide instructions (either on the welcome page or a new page) about how to create a python library to run the notebooks.

Question: should this be 1 environment or 1 per data format?

**Comment by kylebarron** [comment]
I think I'd tend towards one environment _per format_ because:

- There may be large dependencies that users who aren't using a format don't want to incur/figure out how to download
- I'd guess most people will be using only one or two formats, not all of them. I.e. maybe the raster formats but not vector or point cloud.
- There could be version conflicts between environments

**Comment by wildintellect** [comment]
Lets make a folder of `conda.yml`? I think this is what AWS does (goes to look for example)...
I can see at least 2 environments (python, R), on the fence about if we need 1 per format. That would be simpler to maintain/avoid conflicts, and you wouldn't need to test every notebook on every update. However there's so much overlap and really we do push for compatibility with everything. The biggest issue is size, geopandas does not necessarily need Xarray - but if you're doing xarray you might as well have geopandas.

Either way, any notebooks with executable code should list the dependencies and also link to the env.yml if we have it.
